### PR TITLE
Fix for router registrations, css changes mentioned by UX

### PR DESCRIPTION
**Pull request by srowhani**
#patch#

### CODE REVIEW

**Comment by srowhani** [comment]
screen shot 2016-06-23 at 9 56 41 am
screen shot 2016-06-23 at 9 56 25 am

**Comment by sglanzer** [comment]
Is that the new focus look specified by UX for navigation items?  I thought they were referring to Network/System not showing focus, but I may be out of the loop

**Comment by srowhani** [comment]
Nah that's something else they specified

**Comment by sglanzer** [comment]
k, cool

**Comment by sglanzer** [comment]
Approved

**Comment by sglanzer** [comment]
Approved

**Comment by srowhani** [comment]
I have more changes, lets hold up on merge

**Comment by srowhani** [comment]
Approved :+1:

**Comment by sglanzer** [comment]
Approved

**Pull request merged**
